namespace MoreDoors.Data;

// Generated by DataUpdater
internal class DoorNames
{
    public const string ARCHIVE = "Archive";
    public const string BARDOON = "Bardoon";
    public const string BROKEN = "Broken";
    public const string BURIED_GEO = "Buried Geo";
    public const string CANYON = "Canyon";
    public const string CORE = "Core";
    public const string CROWN = "Crown";
    public const string DARKNEST = "Darknest";
    public const string FALSE = "False";
    public const string FLOODED_STAG = "Flooded Stag";
    public const string FOUNTAIN = "Fountain";
    public const string FRAGILE = "Fragile";
    public const string FUNGAL = "Fungal";
    public const string GARDEN = "Garden";
    public const string HEART = "Heart";
    public const string HIVE = "Hive";
    public const string ISMA = "Isma";
    public const string JONI = "Joni";
    public const string JUNK = "Junk";
    public const string LAKE = "Lake";
    public const string MANTIS = "Mantis";
    public const string MOSS = "Moss";
    public const string MOTHWING = "Mothwing";
    public const string NEST = "Nest";
    public const string OVERGROWN = "Overgrown";
    public const string PAIN = "Pain";
    public const string SANCTUM = "Sanctum";
    public const string SHADE = "Shade";
    public const string TRAITOR = "Traitor";
    public const string VILLAGE = "Village";
}
